### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by SorrowX** [liyongleihf2006/getImageMeanColor#1]
最好在源码
var canvasHeight,imageHeight,top=0;
var image = new Image();
image.src= imageUrl;
的下面加上
image.crossOrigin = "anonymous";
来解决Canvas跨域的问题

**Comment by liyongleihf2006** [comment]
好的 好的

我晚上回去把跨域问题解决了

感谢感谢

感谢支持

**Comment by liyongleihf2006** [comment]
我已经修复了ie10+的跨域问题了哈。
感谢🙏
